AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  AvailabilityZone:
    Description: Availability zones to use for instance
    Type: AWS::EC2::AvailabilityZone::Name
    Default: eu-central-1a
  ImageId:
    Description: Base AMI's image ID
    Type: AWS::EC2::Image::Id
    Default: ami-1e339e71
  SSHKey:
    Description: SSH KeyName
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: 'true'
            VolumeSize: 10
            VolumeType: gp2
      ImageId: !Ref ImageId
      InstanceType: t2.micro
      KeyName: !Ref SSHKey
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          apt-get update
          apt-get --yes install curl python-setuptools python-pip
          easy_install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
          pip install awscli

          # Initialize system with cfn-init
          #cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource MyInstance
